env:
   global:
     - CONAN_STABLE_BRANCH_PATTERN: "master/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 0
     - CONAN_SKIP_CHECK_CREDENTIALS: 1

sudo: required
language: cpp
  
linux: &linux
  os: linux
  dist: cosmic
  services:
    - docker

matrix:
  fast_finish: true
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_UPLOAD=""
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_SKIP_CHECK_CREDENTIALS=0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
